version: '3'

services:
  webserver:
    build: ./inference_container
    container_name: bachelorproef-deployement-with-sentiment-test
    networks:
     - E-mail_network
    ports:
      - 80:80

networks:
  E-mail_network: